// <auto-generated />
using System;
using AnthillCommon.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Project.Data.Migrations
{
    [DbContext(typeof(CommonContext))]
    [Migration("20211027133329_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnthillCommon.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 0)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdateTime")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Country_1",
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 817, DateTimeKind.Local).AddTicks(201),
                            Name = "City_1",
                            State = "State_1",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 817, DateTimeKind.Local).AddTicks(9835)
                        },
                        new
                        {
                            Id = 2,
                            Country = "Country_2",
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(307),
                            Name = "City_2",
                            State = "State_2",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(324)
                        },
                        new
                        {
                            Id = 3,
                            Country = "Country_3",
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(346),
                            Name = "City_3",
                            State = "State_3",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(349)
                        },
                        new
                        {
                            Id = 4,
                            Country = "Country_4",
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(357),
                            Name = "City_4",
                            State = "State_4",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(358)
                        },
                        new
                        {
                            Id = 5,
                            Country = "Country_5",
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(365),
                            Name = "City_5",
                            State = "State_5",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(366)
                        },
                        new
                        {
                            Id = 6,
                            Country = "Country_6",
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(378),
                            Name = "City_6",
                            State = "State_6",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(381)
                        },
                        new
                        {
                            Id = 7,
                            Country = "Country_7",
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(388),
                            Name = "City_7",
                            State = "State_7",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(389)
                        },
                        new
                        {
                            Id = 8,
                            Country = "Country_8",
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(396),
                            Name = "City_8",
                            State = "State_8",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(398)
                        },
                        new
                        {
                            Id = 9,
                            Country = "Country_9",
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(404),
                            Name = "City_9",
                            State = "State_9",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(405)
                        },
                        new
                        {
                            Id = 10,
                            Country = "Country_10",
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(415),
                            Name = "City_10",
                            State = "State_10",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(417)
                        });
                });

            modelBuilder.Entity("AnthillCommon.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Office");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address_1",
                            CityId = 1,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(3432),
                            Name = "Office_1",
                            OrganizationId = 1,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(3767)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address_2",
                            CityId = 2,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5317),
                            Name = "Office_2",
                            OrganizationId = 2,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5334)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address_3",
                            CityId = 3,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5409),
                            Name = "Office_3",
                            OrganizationId = 3,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5412)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Address_4",
                            CityId = 4,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5418),
                            Name = "Office_4",
                            OrganizationId = 4,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5420)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Address_5",
                            CityId = 5,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5426),
                            Name = "Office_5",
                            OrganizationId = 5,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5427)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Address_6",
                            CityId = 6,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5437),
                            Name = "Office_6",
                            OrganizationId = 6,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5440)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Address_7",
                            CityId = 7,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5445),
                            Name = "Office_7",
                            OrganizationId = 7,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5446)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Address_8",
                            CityId = 8,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5452),
                            Name = "Office_8",
                            OrganizationId = 8,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5453)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Address_9",
                            CityId = 9,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5458),
                            Name = "Office_9",
                            OrganizationId = 9,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5460)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Address_10",
                            CityId = 10,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5468),
                            Name = "Office_10",
                            OrganizationId = 10,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(5470)
                        });
                });

            modelBuilder.Entity("AnthillCommon.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdateTime")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Organization");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(1384),
                            Name = "Organisation_1",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(1725)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2118),
                            Name = "Organisation_2",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2134)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2153),
                            Name = "Organisation_3",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2157)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2161),
                            Name = "Organisation_4",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2162)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2167),
                            Name = "Organisation_5",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2168)
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2176),
                            Name = "Organisation_6",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2178)
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2182),
                            Name = "Organisation_7",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2183)
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2187),
                            Name = "Organisation_8",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2189)
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2193),
                            Name = "Organisation_9",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2194)
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2200),
                            Name = "Organisation_10",
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(2202)
                        });
                });

            modelBuilder.Entity("AnthillCommon.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BirthDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsFired")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2021, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(7767),
                            Email = "Mail_0",
                            FirstName = "FirstName_0",
                            Gender = "RandomGender_0",
                            IsFired = false,
                            LastName = "LastName_0",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(8103)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2021, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9453),
                            Email = "Mail_1",
                            FirstName = "FirstName_1",
                            Gender = "RandomGender_1",
                            IsFired = false,
                            LastName = "LastName_1",
                            OfficeId = 2,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9468)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2021, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9523),
                            Email = "Mail_2",
                            FirstName = "FirstName_2",
                            Gender = "RandomGender_2",
                            IsFired = false,
                            LastName = "LastName_2",
                            OfficeId = 3,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9525)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2021, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9537),
                            Email = "Mail_3",
                            FirstName = "FirstName_3",
                            Gender = "RandomGender_3",
                            IsFired = false,
                            LastName = "LastName_3",
                            OfficeId = 4,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9538)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2021, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9549),
                            Email = "Mail_4",
                            FirstName = "FirstName_4",
                            Gender = "RandomGender_4",
                            IsFired = false,
                            LastName = "LastName_4",
                            OfficeId = 5,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9550)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2021, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9565),
                            Email = "Mail_5",
                            FirstName = "FirstName_5",
                            Gender = "RandomGender_5",
                            IsFired = false,
                            LastName = "LastName_5",
                            OfficeId = 6,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9567)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2021, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9578),
                            Email = "Mail_6",
                            FirstName = "FirstName_6",
                            Gender = "RandomGender_6",
                            IsFired = false,
                            LastName = "LastName_6",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9579)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2021, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9590),
                            Email = "Mail_7",
                            FirstName = "FirstName_7",
                            Gender = "RandomGender_7",
                            IsFired = false,
                            LastName = "LastName_7",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9591)
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2021, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9601),
                            Email = "Mail_8",
                            FirstName = "FirstName_8",
                            Gender = "RandomGender_8",
                            IsFired = false,
                            LastName = "LastName_8",
                            OfficeId = 9,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9603)
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(2021, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9616),
                            Email = "Mail_9",
                            FirstName = "FirstName_9",
                            Gender = "RandomGender_9",
                            IsFired = false,
                            LastName = "LastName_9",
                            OfficeId = 10,
                            UpdateTime = new DateTime(2021, 10, 27, 16, 33, 28, 818, DateTimeKind.Local).AddTicks(9617)
                        });
                });

            modelBuilder.Entity("Project.Data.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdateTime")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("AnthillCommon.Models.Office", b =>
                {
                    b.HasOne("AnthillCommon.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("AnthillCommon.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.Navigation("City");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AnthillCommon.Models.User", b =>
                {
                    b.HasOne("AnthillCommon.Models.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });
#pragma warning restore 612, 618
        }
    }
}
