// <auto-generated />
using System;
using AnthillCommon.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Project.Data.Migrations
{
    [DbContext(typeof(CommonContext))]
    [Migration("20211109084554_accountChages")]
    partial class accountChages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnthillCommon.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("SubscriptionVersionId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("AnthillCommon.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 0)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdateTime")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Country_1",
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 253, DateTimeKind.Local).AddTicks(9969),
                            Name = "City_1",
                            State = "State_1",
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(123)
                        },
                        new
                        {
                            Id = 2,
                            Country = "Country_2",
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(595),
                            Name = "City_2",
                            State = "State_2",
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(610)
                        },
                        new
                        {
                            Id = 3,
                            Country = "Country_3",
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(630),
                            Name = "City_3",
                            State = "State_3",
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(633)
                        },
                        new
                        {
                            Id = 4,
                            Country = "Country_4",
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(640),
                            Name = "City_4",
                            State = "State_4",
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(641)
                        },
                        new
                        {
                            Id = 5,
                            Country = "Country_5",
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(648),
                            Name = "City_5",
                            State = "State_5",
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(650)
                        });
                });

            modelBuilder.Entity("AnthillCommon.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Office");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address_1",
                            CityId = 1,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(3697),
                            Name = "Office_1",
                            OrganizationId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(4092)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address_2",
                            CityId = 1,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5597),
                            Name = "Office_2",
                            OrganizationId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5613)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address_3",
                            CityId = 2,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5681),
                            Name = "Office_3",
                            OrganizationId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5685)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Address_4",
                            CityId = 2,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5691),
                            Name = "Office_4",
                            OrganizationId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5693)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Address_5",
                            CityId = 3,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5699),
                            Name = "Office_5",
                            OrganizationId = 3,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5700)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Address_6",
                            CityId = 3,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5710),
                            Name = "Office_6",
                            OrganizationId = 3,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5712)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Address_7",
                            CityId = 4,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5718),
                            Name = "Office_7",
                            OrganizationId = 4,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5719)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Address_8",
                            CityId = 4,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5725),
                            Name = "Office_8",
                            OrganizationId = 4,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5727)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Address_9",
                            CityId = 5,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5732),
                            Name = "Office_9",
                            OrganizationId = 5,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5734)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Address_10",
                            CityId = 5,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5742),
                            Name = "Office_10",
                            OrganizationId = 5,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(5744)
                        });
                });

            modelBuilder.Entity("AnthillCommon.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdateTime")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Organization");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(1619),
                            Name = "Organisation_1",
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(1955)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(2405),
                            Name = "Organisation_2",
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(2418)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(2445),
                            Name = "Organisation_3",
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(2448)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(2452),
                            Name = "Organisation_4",
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(2453)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(2457),
                            Name = "Organisation_5",
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(2458)
                        });
                });

            modelBuilder.Entity("AnthillCommon.Models.RefreshToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.HasIndex("AccountId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("AnthillCommon.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscription");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 0.0,
                            Name = "Basic",
                            SubscriptionType = 1
                        });
                });

            modelBuilder.Entity("AnthillCommon.Models.SubscriptionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionVersion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 14,
                            Name = "Trial"
                        });
                });

            modelBuilder.Entity("AnthillCommon.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BirthDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsFired")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasMaxLength(19)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(8035),
                            Email = "Mail_0",
                            FirstName = "FirstName_0",
                            Gender = "RandomGender_0",
                            IsFired = false,
                            LastName = "LastName_0",
                            OfficeId = 3,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(8364)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9707),
                            Email = "Mail_1",
                            FirstName = "FirstName_1",
                            Gender = "RandomGender_1",
                            IsFired = false,
                            LastName = "LastName_1",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9719)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9791),
                            Email = "Mail_2",
                            FirstName = "FirstName_2",
                            Gender = "RandomGender_2",
                            IsFired = false,
                            LastName = "LastName_2",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9793)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9805),
                            Email = "Mail_3",
                            FirstName = "FirstName_3",
                            Gender = "RandomGender_3",
                            IsFired = false,
                            LastName = "LastName_3",
                            OfficeId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9807)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9818),
                            Email = "Mail_4",
                            FirstName = "FirstName_4",
                            Gender = "RandomGender_4",
                            IsFired = false,
                            LastName = "LastName_4",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9820)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9836),
                            Email = "Mail_5",
                            FirstName = "FirstName_5",
                            Gender = "RandomGender_5",
                            IsFired = false,
                            LastName = "LastName_5",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9838)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9849),
                            Email = "Mail_6",
                            FirstName = "FirstName_6",
                            Gender = "RandomGender_6",
                            IsFired = false,
                            LastName = "LastName_6",
                            OfficeId = 3,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9850)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9939),
                            Email = "Mail_7",
                            FirstName = "FirstName_7",
                            Gender = "RandomGender_7",
                            IsFired = false,
                            LastName = "LastName_7",
                            OfficeId = 4,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9941)
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9953),
                            Email = "Mail_8",
                            FirstName = "FirstName_8",
                            Gender = "RandomGender_8",
                            IsFired = false,
                            LastName = "LastName_8",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9955)
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9970),
                            Email = "Mail_9",
                            FirstName = "FirstName_9",
                            Gender = "RandomGender_9",
                            IsFired = false,
                            LastName = "LastName_9",
                            OfficeId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9972)
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9983),
                            Email = "Mail_10",
                            FirstName = "FirstName_10",
                            Gender = "RandomGender_10",
                            IsFired = false,
                            LastName = "LastName_10",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9985)
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9996),
                            Email = "Mail_11",
                            FirstName = "FirstName_11",
                            Gender = "RandomGender_11",
                            IsFired = false,
                            LastName = "LastName_11",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 255, DateTimeKind.Local).AddTicks(9997)
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(9),
                            Email = "Mail_12",
                            FirstName = "FirstName_12",
                            Gender = "RandomGender_12",
                            IsFired = false,
                            LastName = "LastName_12",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(10)
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(21),
                            Email = "Mail_13",
                            FirstName = "FirstName_13",
                            Gender = "RandomGender_13",
                            IsFired = false,
                            LastName = "LastName_13",
                            OfficeId = 6,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(22)
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(33),
                            Email = "Mail_14",
                            FirstName = "FirstName_14",
                            Gender = "RandomGender_14",
                            IsFired = false,
                            LastName = "LastName_14",
                            OfficeId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(35)
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(46),
                            Email = "Mail_15",
                            FirstName = "FirstName_15",
                            Gender = "RandomGender_15",
                            IsFired = false,
                            LastName = "LastName_15",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(47)
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(58),
                            Email = "Mail_16",
                            FirstName = "FirstName_16",
                            Gender = "RandomGender_16",
                            IsFired = false,
                            LastName = "LastName_16",
                            OfficeId = 4,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(59)
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(74),
                            Email = "Mail_17",
                            FirstName = "FirstName_17",
                            Gender = "RandomGender_17",
                            IsFired = false,
                            LastName = "LastName_17",
                            OfficeId = 9,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(75)
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(86),
                            Email = "Mail_18",
                            FirstName = "FirstName_18",
                            Gender = "RandomGender_18",
                            IsFired = false,
                            LastName = "LastName_18",
                            OfficeId = 4,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(88)
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(99),
                            Email = "Mail_19",
                            FirstName = "FirstName_19",
                            Gender = "RandomGender_19",
                            IsFired = false,
                            LastName = "LastName_19",
                            OfficeId = 6,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(100)
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(111),
                            Email = "Mail_20",
                            FirstName = "FirstName_20",
                            Gender = "RandomGender_20",
                            IsFired = false,
                            LastName = "LastName_20",
                            OfficeId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(112)
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(123),
                            Email = "Mail_21",
                            FirstName = "FirstName_21",
                            Gender = "RandomGender_21",
                            IsFired = false,
                            LastName = "LastName_21",
                            OfficeId = 9,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(125)
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(135),
                            Email = "Mail_22",
                            FirstName = "FirstName_22",
                            Gender = "RandomGender_22",
                            IsFired = false,
                            LastName = "LastName_22",
                            OfficeId = 5,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(137)
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(148),
                            Email = "Mail_23",
                            FirstName = "FirstName_23",
                            Gender = "RandomGender_23",
                            IsFired = false,
                            LastName = "LastName_23",
                            OfficeId = 10,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(149)
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(160),
                            Email = "Mail_24",
                            FirstName = "FirstName_24",
                            Gender = "RandomGender_24",
                            IsFired = false,
                            LastName = "LastName_24",
                            OfficeId = 5,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(162)
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(172),
                            Email = "Mail_25",
                            FirstName = "FirstName_25",
                            Gender = "RandomGender_25",
                            IsFired = false,
                            LastName = "LastName_25",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(174)
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(245),
                            Email = "Mail_26",
                            FirstName = "FirstName_26",
                            Gender = "RandomGender_26",
                            IsFired = false,
                            LastName = "LastName_26",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(247)
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(260),
                            Email = "Mail_27",
                            FirstName = "FirstName_27",
                            Gender = "RandomGender_27",
                            IsFired = false,
                            LastName = "LastName_27",
                            OfficeId = 3,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(262)
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(273),
                            Email = "Mail_28",
                            FirstName = "FirstName_28",
                            Gender = "RandomGender_28",
                            IsFired = false,
                            LastName = "LastName_28",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(275)
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(286),
                            Email = "Mail_29",
                            FirstName = "FirstName_29",
                            Gender = "RandomGender_29",
                            IsFired = false,
                            LastName = "LastName_29",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(287)
                        },
                        new
                        {
                            Id = 31,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(298),
                            Email = "Mail_30",
                            FirstName = "FirstName_30",
                            Gender = "RandomGender_30",
                            IsFired = false,
                            LastName = "LastName_30",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(300)
                        },
                        new
                        {
                            Id = 32,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(311),
                            Email = "Mail_31",
                            FirstName = "FirstName_31",
                            Gender = "RandomGender_31",
                            IsFired = false,
                            LastName = "LastName_31",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(312)
                        },
                        new
                        {
                            Id = 33,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(323),
                            Email = "Mail_32",
                            FirstName = "FirstName_32",
                            Gender = "RandomGender_32",
                            IsFired = false,
                            LastName = "LastName_32",
                            OfficeId = 5,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(325)
                        },
                        new
                        {
                            Id = 34,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(340),
                            Email = "Mail_33",
                            FirstName = "FirstName_33",
                            Gender = "RandomGender_33",
                            IsFired = false,
                            LastName = "LastName_33",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(341)
                        },
                        new
                        {
                            Id = 35,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(352),
                            Email = "Mail_34",
                            FirstName = "FirstName_34",
                            Gender = "RandomGender_34",
                            IsFired = false,
                            LastName = "LastName_34",
                            OfficeId = 4,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(353)
                        },
                        new
                        {
                            Id = 36,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(365),
                            Email = "Mail_35",
                            FirstName = "FirstName_35",
                            Gender = "RandomGender_35",
                            IsFired = false,
                            LastName = "LastName_35",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(366)
                        },
                        new
                        {
                            Id = 37,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(378),
                            Email = "Mail_36",
                            FirstName = "FirstName_36",
                            Gender = "RandomGender_36",
                            IsFired = false,
                            LastName = "LastName_36",
                            OfficeId = 5,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(379)
                        },
                        new
                        {
                            Id = 38,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(390),
                            Email = "Mail_37",
                            FirstName = "FirstName_37",
                            Gender = "RandomGender_37",
                            IsFired = false,
                            LastName = "LastName_37",
                            OfficeId = 5,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(392)
                        },
                        new
                        {
                            Id = 39,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(403),
                            Email = "Mail_38",
                            FirstName = "FirstName_38",
                            Gender = "RandomGender_38",
                            IsFired = false,
                            LastName = "LastName_38",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(404)
                        },
                        new
                        {
                            Id = 40,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(415),
                            Email = "Mail_39",
                            FirstName = "FirstName_39",
                            Gender = "RandomGender_39",
                            IsFired = false,
                            LastName = "LastName_39",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(416)
                        },
                        new
                        {
                            Id = 41,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(427),
                            Email = "Mail_40",
                            FirstName = "FirstName_40",
                            Gender = "RandomGender_40",
                            IsFired = false,
                            LastName = "LastName_40",
                            OfficeId = 6,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(429)
                        },
                        new
                        {
                            Id = 42,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(440),
                            Email = "Mail_41",
                            FirstName = "FirstName_41",
                            Gender = "RandomGender_41",
                            IsFired = false,
                            LastName = "LastName_41",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(441)
                        },
                        new
                        {
                            Id = 43,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(452),
                            Email = "Mail_42",
                            FirstName = "FirstName_42",
                            Gender = "RandomGender_42",
                            IsFired = false,
                            LastName = "LastName_42",
                            OfficeId = 4,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(453)
                        },
                        new
                        {
                            Id = 44,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(464),
                            Email = "Mail_43",
                            FirstName = "FirstName_43",
                            Gender = "RandomGender_43",
                            IsFired = false,
                            LastName = "LastName_43",
                            OfficeId = 10,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(466)
                        },
                        new
                        {
                            Id = 45,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(477),
                            Email = "Mail_44",
                            FirstName = "FirstName_44",
                            Gender = "RandomGender_44",
                            IsFired = false,
                            LastName = "LastName_44",
                            OfficeId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(478)
                        },
                        new
                        {
                            Id = 46,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(489),
                            Email = "Mail_45",
                            FirstName = "FirstName_45",
                            Gender = "RandomGender_45",
                            IsFired = false,
                            LastName = "LastName_45",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(490)
                        },
                        new
                        {
                            Id = 47,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(590),
                            Email = "Mail_46",
                            FirstName = "FirstName_46",
                            Gender = "RandomGender_46",
                            IsFired = false,
                            LastName = "LastName_46",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(591)
                        },
                        new
                        {
                            Id = 48,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(603),
                            Email = "Mail_47",
                            FirstName = "FirstName_47",
                            Gender = "RandomGender_47",
                            IsFired = false,
                            LastName = "LastName_47",
                            OfficeId = 6,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(605)
                        },
                        new
                        {
                            Id = 49,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(616),
                            Email = "Mail_48",
                            FirstName = "FirstName_48",
                            Gender = "RandomGender_48",
                            IsFired = false,
                            LastName = "LastName_48",
                            OfficeId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(617)
                        },
                        new
                        {
                            Id = 50,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(628),
                            Email = "Mail_49",
                            FirstName = "FirstName_49",
                            Gender = "RandomGender_49",
                            IsFired = false,
                            LastName = "LastName_49",
                            OfficeId = 10,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(630)
                        },
                        new
                        {
                            Id = 51,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(641),
                            Email = "Mail_50",
                            FirstName = "FirstName_50",
                            Gender = "RandomGender_50",
                            IsFired = false,
                            LastName = "LastName_50",
                            OfficeId = 9,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(642)
                        },
                        new
                        {
                            Id = 52,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(653),
                            Email = "Mail_51",
                            FirstName = "FirstName_51",
                            Gender = "RandomGender_51",
                            IsFired = false,
                            LastName = "LastName_51",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(655)
                        },
                        new
                        {
                            Id = 53,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(666),
                            Email = "Mail_52",
                            FirstName = "FirstName_52",
                            Gender = "RandomGender_52",
                            IsFired = false,
                            LastName = "LastName_52",
                            OfficeId = 9,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(667)
                        },
                        new
                        {
                            Id = 54,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(678),
                            Email = "Mail_53",
                            FirstName = "FirstName_53",
                            Gender = "RandomGender_53",
                            IsFired = false,
                            LastName = "LastName_53",
                            OfficeId = 9,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(680)
                        },
                        new
                        {
                            Id = 55,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(690),
                            Email = "Mail_54",
                            FirstName = "FirstName_54",
                            Gender = "RandomGender_54",
                            IsFired = false,
                            LastName = "LastName_54",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(692)
                        },
                        new
                        {
                            Id = 56,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(703),
                            Email = "Mail_55",
                            FirstName = "FirstName_55",
                            Gender = "RandomGender_55",
                            IsFired = false,
                            LastName = "LastName_55",
                            OfficeId = 4,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(704)
                        },
                        new
                        {
                            Id = 57,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(715),
                            Email = "Mail_56",
                            FirstName = "FirstName_56",
                            Gender = "RandomGender_56",
                            IsFired = false,
                            LastName = "LastName_56",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(717)
                        },
                        new
                        {
                            Id = 58,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(728),
                            Email = "Mail_57",
                            FirstName = "FirstName_57",
                            Gender = "RandomGender_57",
                            IsFired = false,
                            LastName = "LastName_57",
                            OfficeId = 9,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(730)
                        },
                        new
                        {
                            Id = 59,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(741),
                            Email = "Mail_58",
                            FirstName = "FirstName_58",
                            Gender = "RandomGender_58",
                            IsFired = false,
                            LastName = "LastName_58",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(742)
                        },
                        new
                        {
                            Id = 60,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(753),
                            Email = "Mail_59",
                            FirstName = "FirstName_59",
                            Gender = "RandomGender_59",
                            IsFired = false,
                            LastName = "LastName_59",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(755)
                        },
                        new
                        {
                            Id = 61,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(766),
                            Email = "Mail_60",
                            FirstName = "FirstName_60",
                            Gender = "RandomGender_60",
                            IsFired = false,
                            LastName = "LastName_60",
                            OfficeId = 4,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(767)
                        },
                        new
                        {
                            Id = 62,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(778),
                            Email = "Mail_61",
                            FirstName = "FirstName_61",
                            Gender = "RandomGender_61",
                            IsFired = false,
                            LastName = "LastName_61",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(779)
                        },
                        new
                        {
                            Id = 63,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(790),
                            Email = "Mail_62",
                            FirstName = "FirstName_62",
                            Gender = "RandomGender_62",
                            IsFired = false,
                            LastName = "LastName_62",
                            OfficeId = 6,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(792)
                        },
                        new
                        {
                            Id = 64,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(802),
                            Email = "Mail_63",
                            FirstName = "FirstName_63",
                            Gender = "RandomGender_63",
                            IsFired = false,
                            LastName = "LastName_63",
                            OfficeId = 9,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(804)
                        },
                        new
                        {
                            Id = 65,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(815),
                            Email = "Mail_64",
                            FirstName = "FirstName_64",
                            Gender = "RandomGender_64",
                            IsFired = false,
                            LastName = "LastName_64",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(816)
                        },
                        new
                        {
                            Id = 66,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(889),
                            Email = "Mail_65",
                            FirstName = "FirstName_65",
                            Gender = "RandomGender_65",
                            IsFired = false,
                            LastName = "LastName_65",
                            OfficeId = 10,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(890)
                        },
                        new
                        {
                            Id = 67,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(902),
                            Email = "Mail_66",
                            FirstName = "FirstName_66",
                            Gender = "RandomGender_66",
                            IsFired = false,
                            LastName = "LastName_66",
                            OfficeId = 4,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(903)
                        },
                        new
                        {
                            Id = 68,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(914),
                            Email = "Mail_67",
                            FirstName = "FirstName_67",
                            Gender = "RandomGender_67",
                            IsFired = false,
                            LastName = "LastName_67",
                            OfficeId = 6,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(916)
                        },
                        new
                        {
                            Id = 69,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(926),
                            Email = "Mail_68",
                            FirstName = "FirstName_68",
                            Gender = "RandomGender_68",
                            IsFired = false,
                            LastName = "LastName_68",
                            OfficeId = 3,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(928)
                        },
                        new
                        {
                            Id = 70,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(939),
                            Email = "Mail_69",
                            FirstName = "FirstName_69",
                            Gender = "RandomGender_69",
                            IsFired = false,
                            LastName = "LastName_69",
                            OfficeId = 4,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(940)
                        },
                        new
                        {
                            Id = 71,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(951),
                            Email = "Mail_70",
                            FirstName = "FirstName_70",
                            Gender = "RandomGender_70",
                            IsFired = false,
                            LastName = "LastName_70",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(952)
                        },
                        new
                        {
                            Id = 72,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(963),
                            Email = "Mail_71",
                            FirstName = "FirstName_71",
                            Gender = "RandomGender_71",
                            IsFired = false,
                            LastName = "LastName_71",
                            OfficeId = 9,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(965)
                        },
                        new
                        {
                            Id = 73,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(976),
                            Email = "Mail_72",
                            FirstName = "FirstName_72",
                            Gender = "RandomGender_72",
                            IsFired = false,
                            LastName = "LastName_72",
                            OfficeId = 3,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(977)
                        },
                        new
                        {
                            Id = 74,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(988),
                            Email = "Mail_73",
                            FirstName = "FirstName_73",
                            Gender = "RandomGender_73",
                            IsFired = false,
                            LastName = "LastName_73",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(989)
                        },
                        new
                        {
                            Id = 75,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1000),
                            Email = "Mail_74",
                            FirstName = "FirstName_74",
                            Gender = "RandomGender_74",
                            IsFired = false,
                            LastName = "LastName_74",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1002)
                        },
                        new
                        {
                            Id = 76,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1013),
                            Email = "Mail_75",
                            FirstName = "FirstName_75",
                            Gender = "RandomGender_75",
                            IsFired = false,
                            LastName = "LastName_75",
                            OfficeId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1015)
                        },
                        new
                        {
                            Id = 77,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1025),
                            Email = "Mail_76",
                            FirstName = "FirstName_76",
                            Gender = "RandomGender_76",
                            IsFired = false,
                            LastName = "LastName_76",
                            OfficeId = 6,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1027)
                        },
                        new
                        {
                            Id = 78,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1038),
                            Email = "Mail_77",
                            FirstName = "FirstName_77",
                            Gender = "RandomGender_77",
                            IsFired = false,
                            LastName = "LastName_77",
                            OfficeId = 5,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1039)
                        },
                        new
                        {
                            Id = 79,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1050),
                            Email = "Mail_78",
                            FirstName = "FirstName_78",
                            Gender = "RandomGender_78",
                            IsFired = false,
                            LastName = "LastName_78",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1052)
                        },
                        new
                        {
                            Id = 80,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1063),
                            Email = "Mail_79",
                            FirstName = "FirstName_79",
                            Gender = "RandomGender_79",
                            IsFired = false,
                            LastName = "LastName_79",
                            OfficeId = 9,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1064)
                        },
                        new
                        {
                            Id = 81,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1075),
                            Email = "Mail_80",
                            FirstName = "FirstName_80",
                            Gender = "RandomGender_80",
                            IsFired = false,
                            LastName = "LastName_80",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1076)
                        },
                        new
                        {
                            Id = 82,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1087),
                            Email = "Mail_81",
                            FirstName = "FirstName_81",
                            Gender = "RandomGender_81",
                            IsFired = false,
                            LastName = "LastName_81",
                            OfficeId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1089)
                        },
                        new
                        {
                            Id = 83,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1100),
                            Email = "Mail_82",
                            FirstName = "FirstName_82",
                            Gender = "RandomGender_82",
                            IsFired = false,
                            LastName = "LastName_82",
                            OfficeId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1101)
                        },
                        new
                        {
                            Id = 84,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1112),
                            Email = "Mail_83",
                            FirstName = "FirstName_83",
                            Gender = "RandomGender_83",
                            IsFired = false,
                            LastName = "LastName_83",
                            OfficeId = 9,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1113)
                        },
                        new
                        {
                            Id = 85,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1124),
                            Email = "Mail_84",
                            FirstName = "FirstName_84",
                            Gender = "RandomGender_84",
                            IsFired = false,
                            LastName = "LastName_84",
                            OfficeId = 10,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1126)
                        },
                        new
                        {
                            Id = 86,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1194),
                            Email = "Mail_85",
                            FirstName = "FirstName_85",
                            Gender = "RandomGender_85",
                            IsFired = false,
                            LastName = "LastName_85",
                            OfficeId = 1,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1195)
                        },
                        new
                        {
                            Id = 87,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1207),
                            Email = "Mail_86",
                            FirstName = "FirstName_86",
                            Gender = "RandomGender_86",
                            IsFired = false,
                            LastName = "LastName_86",
                            OfficeId = 8,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1208)
                        },
                        new
                        {
                            Id = 88,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1219),
                            Email = "Mail_87",
                            FirstName = "FirstName_87",
                            Gender = "RandomGender_87",
                            IsFired = false,
                            LastName = "LastName_87",
                            OfficeId = 6,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1221)
                        },
                        new
                        {
                            Id = 89,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1232),
                            Email = "Mail_88",
                            FirstName = "FirstName_88",
                            Gender = "RandomGender_88",
                            IsFired = false,
                            LastName = "LastName_88",
                            OfficeId = 5,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1233)
                        },
                        new
                        {
                            Id = 90,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1244),
                            Email = "Mail_89",
                            FirstName = "FirstName_89",
                            Gender = "RandomGender_89",
                            IsFired = false,
                            LastName = "LastName_89",
                            OfficeId = 10,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1245)
                        },
                        new
                        {
                            Id = 91,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1256),
                            Email = "Mail_90",
                            FirstName = "FirstName_90",
                            Gender = "RandomGender_90",
                            IsFired = false,
                            LastName = "LastName_90",
                            OfficeId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1258)
                        },
                        new
                        {
                            Id = 92,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1269),
                            Email = "Mail_91",
                            FirstName = "FirstName_91",
                            Gender = "RandomGender_91",
                            IsFired = false,
                            LastName = "LastName_91",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1270)
                        },
                        new
                        {
                            Id = 93,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1281),
                            Email = "Mail_92",
                            FirstName = "FirstName_92",
                            Gender = "RandomGender_92",
                            IsFired = false,
                            LastName = "LastName_92",
                            OfficeId = 7,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1283)
                        },
                        new
                        {
                            Id = 94,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1293),
                            Email = "Mail_93",
                            FirstName = "FirstName_93",
                            Gender = "RandomGender_93",
                            IsFired = false,
                            LastName = "LastName_93",
                            OfficeId = 6,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1295)
                        },
                        new
                        {
                            Id = 95,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1306),
                            Email = "Mail_94",
                            FirstName = "FirstName_94",
                            Gender = "RandomGender_94",
                            IsFired = false,
                            LastName = "LastName_94",
                            OfficeId = 4,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1307)
                        },
                        new
                        {
                            Id = 96,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1318),
                            Email = "Mail_95",
                            FirstName = "FirstName_95",
                            Gender = "RandomGender_95",
                            IsFired = false,
                            LastName = "LastName_95",
                            OfficeId = 6,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1319)
                        },
                        new
                        {
                            Id = 97,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1330),
                            Email = "Mail_96",
                            FirstName = "FirstName_96",
                            Gender = "RandomGender_96",
                            IsFired = false,
                            LastName = "LastName_96",
                            OfficeId = 5,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1332)
                        },
                        new
                        {
                            Id = 98,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1343),
                            Email = "Mail_97",
                            FirstName = "FirstName_97",
                            Gender = "RandomGender_97",
                            IsFired = false,
                            LastName = "LastName_97",
                            OfficeId = 6,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1344)
                        },
                        new
                        {
                            Id = 99,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1355),
                            Email = "Mail_98",
                            FirstName = "FirstName_98",
                            Gender = "RandomGender_98",
                            IsFired = false,
                            LastName = "LastName_98",
                            OfficeId = 10,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1357)
                        },
                        new
                        {
                            Id = 100,
                            BirthDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreateDate = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1368),
                            Email = "Mail_99",
                            FirstName = "FirstName_99",
                            Gender = "RandomGender_99",
                            IsFired = false,
                            LastName = "LastName_99",
                            OfficeId = 2,
                            UpdateTime = new DateTime(2021, 11, 9, 11, 45, 53, 256, DateTimeKind.Local).AddTicks(1369)
                        });
                });

            modelBuilder.Entity("AnthillCommon.Models.Account", b =>
                {
                    b.HasOne("AnthillCommon.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("AnthillCommon.Models.SubscriptionVersion", "SubscriptionVersion")
                        .WithMany()
                        .HasForeignKey("SubscriptionVersionId");

                    b.Navigation("Subscription");

                    b.Navigation("SubscriptionVersion");
                });

            modelBuilder.Entity("AnthillCommon.Models.Office", b =>
                {
                    b.HasOne("AnthillCommon.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("AnthillCommon.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.Navigation("City");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AnthillCommon.Models.RefreshToken", b =>
                {
                    b.HasOne("AnthillCommon.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AnthillCommon.Models.User", b =>
                {
                    b.HasOne("AnthillCommon.Models.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });
#pragma warning restore 612, 618
        }
    }
}
